version: '3'
services:
  mycat-2:
    build: 
      context: ./
      dockerfile: ./Dockerfile 
    container_name: mycat-2
    volumes:
      - ./config/:/mycat/conf/:ro
      - ./logs/:/mycat/logs/:rw            
    ports:
      - "8067:8066"
      - "9067:9066"
    ulimits:
      nproc: 65535
    hostname: mycat2
#    mem_limit: 1024m
    restart: always
