version: '3'
services:
  haproxy:
    build: 
      context: ./
      dockerfile: ./Dockerfile 
    container_name: haproxy
    volumes:
      - ./config:/usr/local/etc/haproxy:ro                 
    ports:
      - "14001:4001"
      - "14002:4002"
    ulimits:
      nproc: 65535
    hostname: haproxy
#    mem_limit: 1024m
    restart: always
